# Generated by Django 3.2.7 on 2021-09-19 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular author across whole library', primary_key=True, serialize=False),
        ),
    ]
